[package]
org = "ballerina"
name = "ftp"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "./lib/commons-vfs2-@commons.vfs2.version@.jar"
groupId = "org.wso2.org.apache.commons"
artifactId = "commons-vfs2"
version = "@commons.vfs2.version@"

[[platform.java11.dependency]]
path = "./lib/jsch-@jsch.version@.jar"
groupId = "com.jcraft"
artifactId = "jsch"
version = "@jsch.version@"

[[platform.java11.dependency]]
path = "./lib/commons-net-@commons.net.version@.jar"
groupId = "commons-net"
artifactId = "commons-net"
version = "@commons.net.version@"

[[platform.java11.dependency]]
path = "./lib/testng-@testng.version@.jar"
groupId = "org.testng"
artifactId = "testng"
version = "@testng.version@"

[[platform.java11.dependency]]
path = "./lib/MockFtpServer-@mockftpserver.version@.jar"
groupId = "org.mockftpserver"
artifactId = "MockFtpServer"
version = "@mockftpserver.version@"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/bcprov-jdk15on-@bouncycastle.version@.jar"
groupId = "org.bouncycastle"
artifactId = "bcprov-jdk15on"
version = "@bouncycastle.version@"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/sshd-core-@sshd.core.version@.jar"
groupId = "org.apache.sshd"
artifactId = "sshd-core"
version = "@sshd.core.version@"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/ftpserver-core-@ftpserver.core.version@.jar"
groupId = "org.apache.ftpserver"
artifactId = "ftpserver-core"
version = "@ftpserver.core.version@"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/ftplet-api-@ftplet.api.version@.jar"
groupId = "org.apache.ftpserver"
artifactId = "ftplet-api"
version = "@ftplet.api.version@"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/mina-core-@mina.core.version@.jar"
groupId = "org.apache.mina"
artifactId = "mina-core"
version = "@mina.core.version@"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/aopalliance-@aopalliance.version@.jar"
groupId = "aopalliance"
artifactId = "aopalliance"
version = "@aopalliance.version@"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/jcl-over-slf4j-@jcl.slf4j.version@.jar"
groupId = "org.slf4j"
artifactId = "jcl-over-slf4j"
version = "@jcl.slf4j.version@"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/org.wso2.transport.remote-file-system-@wso2.remote.file.system.version@.jar"
groupId = "org.wso2.transport.file"
artifactId = "org.wso2.transport.remote-file-system"
version = "@wso2.remote.file.system.version@"

[[platform.java11.dependency]]
path = "../ftp-native/build/libs/ftp-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "ftp"
version = "@project.version@"

[[platform.java11.dependency]]
path = "../ftp-test-utils/build/libs/ftp-test-utils-@project.version@.jar"
groupId = "org.ballerinalang.stdlib.ftp"
scope = "testOnly"
artifactId = "ftp"
version = "@project.version@"
