[package]
org = "ballerina"
name = "ftp"
version = "2.15.1"
authors = ["Ballerina"]
keywords = ["FTP", "SFTP", "remote file", "file transfer", "client", "service"]
repository = "https://github.com/ballerina-platform/module-ballerina-ftp"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.12.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-vfs2"
version = "2.10.0"
path = "./lib/commons-vfs2-2.10.0.jar"

[[platform.java21.dependency]]
groupId = "com.jcraft"
artifactId = "jsch"
version = "0.1.55"
path = "./lib/jsch-0.1.55.jar"

[[platform.java21.dependency]]
groupId = "commons-net"
artifactId = "commons-net"
version = "3.11.1"
path = "./lib/commons-net-3.11.1.jar"

[[platform.java21.dependency]]
groupId = "commons-io"
artifactId = "commons-io"
version = "2.18.0"
path = "./lib/commons-io-2.18.0.jar"

[[platform.java21.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-lang3"
version = "3.18.0"
path = "./lib/commons-lang3-3.18.0.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "ftp-native"
version = "2.15.1"
path = "../native/build/libs/ftp-native-2.15.1-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "data.jsondata-native"
version = "1.1.2"
path = "./lib/data.jsondata-native-1.1.2.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "data.xmldata-native"
version = "1.5.2"
path = "./lib/data.xmldata-native-1.5.2.jar"


[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "data.csv-native"
version = "0.8.1"
path = "./lib/data.csv-native-0.8.1.jar"
