[package]
org = "ballerina"
name = "ftp"
version = "2.0.0"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "./lib/commons-vfs2-2.8.0.jar"

[[platform.java11.dependency]]
path = "./lib/commons-lang3-3.12.0.jar"

[[platform.java11.dependency]]
path = "./lib/jsch-0.1.54.jar"

[[platform.java11.dependency]]
path = "./lib/commons-net-3.6.jar"

[[platform.java11.dependency]]
path = "./lib/testng-6.14.3.jar"

[[platform.java11.dependency]]
path = "./lib/MockFtpServer-2.7.1.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/sshd-core-1.7.0.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/ftpserver-core-1.1.1.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/ftplet-api-1.1.1.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/mina-core-2.0.16.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/aopalliance-1.0.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/jcl-over-slf4j-1.7.21.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "../native/build/libs/ftp-native-2.0.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/ftp-test-utils-2.0.0-SNAPSHOT.jar"
scope = "testOnly"
