[package]
org = "ballerina"
name = "ftp"
version = "2.11.1"
authors = ["Ballerina"]
keywords = ["FTP", "SFTP", "remote file", "file transfer", "client", "service"]
repository = "https://github.com/ballerina-platform/module-ballerina-ftp"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.10.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-vfs2"
version = "2.10.0"
path = "./lib/commons-vfs2-2.10.0.jar"

[[platform.java17.dependency]]
groupId = "com.jcraft"
artifactId = "jsch"
version = "0.1.55"
path = "./lib/jsch-0.1.55.jar"

[[platform.java17.dependency]]
groupId = "commons-net"
artifactId = "commons-net"
version = "3.11.1"
path = "./lib/commons-net-3.11.1.jar"

[[platform.java17.dependency]]
groupId = "commons-io"
artifactId = "commons-io"
version = "2.18.0"
path = "./lib/commons-io-2.18.0.jar"

[[platform.java17.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-lang3"
version = "3.17.0"
path = "./lib/commons-lang3-3.17.0.jar"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "ftp-native"
version = "2.11.1"
path = "../native/build/libs/ftp-native-2.11.1-SNAPSHOT.jar"
