[package]
org = "ballerina"
name = "ftp"
version = "2.5.1"
authors = ["Ballerina"]
keywords = ["FTP", "SFTP", "remote file", "file transfer", "client", "service"]
repository = "https://github.com/ballerina-platform/module-ballerina-ftp"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.3.0"

[[platform.java11.dependency]]
path = "./lib/commons-vfs2-2.8.0.jar"

[[platform.java11.dependency]]
path = "./lib/jsch-0.1.54.jar"

[[platform.java11.dependency]]
path = "./lib/commons-net-3.9.0.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/MockFtpServer-2.7.1.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/sshd-core-1.7.0.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/ftpserver-core-1.1.1.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/ftplet-api-1.1.1.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/mina-core-2.1.5.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/aopalliance-1.0.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/jcl-over-slf4j-1.7.21.jar"
scope = "testOnly"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "ftp-native"
version = "2.5.1"
path = "../native/build/libs/ftp-native-2.5.1-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/ftp-test-utils-2.5.1-SNAPSHOT.jar"
scope = "testOnly"
