[package]
org = "ballerina"
name = "ftp_client_tests"
version = "2.17.1"

[[dependency]]
org = "ballerina"
name = "ftp_test_commons"
repository = "local"
version = "2.17.1"

[platform.java21]
graalvmCompatible = true
